json.sessionToken user.session_token
json.id user.id
json.firstName user.first_name
json.lastName user.last_name
json.username user.username
json.email user.email
json.img_url user.img_url
json.description user.description
json.latitude user.latitude
json.longitude user.longitude
